### PR TITLE
Absolute parent fix

### LINKED ISSUE #157: components in popover body don't receive events in tests
This works fine in live usage, but only fails in tests. The following integration test fails with "Expected 5 assertions, but 4 were run". The dummy component is just a component.js with a class for the div.

```javascript
test('button in bare popover component receives events', function(assert) {
  assert.expect(5);

  this.on('click', function() {
    console.debug('button clicked!');
    assert.ok(true, 'the eventhandler is fired');
  });
  
  this.render(hbs`
    {{#dummy-component}}
      {{#popover-on-component}}
        <button class="my-button" {{action 'click'}}>test button</button>
      {{/popover-on-component}}
    {{/dummy-component}}
  `);

  const done = assert.async();

  let $target = $('.dummy-component');
  assertTooltipNotVisible(assert);
  triggerTooltipTargetEvent($target, 'mouseenter');
  assertTooltipRendered(assert);
  assertTooltipVisible(assert);
  
  let $button = $('.my-button');
  assert.equal($button.length, 1, 'the button can be found');
  $button.trigger('click');

  Ember.run.later(() => {
		done();
  }, 100);
});
```

I'm on ember(-cli) 2.10.0, ember-tooltips 2.7.1

### PR DESCRIPTION
**Pull request by sir-dunxalot**
This PR makes tooltips render as a child of the Ember app's `rootElement` if it's defined. When `rootElement` is not defined, tooltips will still render as a child of the body.

This change fixes event delegation issues in test suites where events and actions were fired but not caught by the Ember app of parent components. This fixes #157 and #141.

### CODE REVIEW

File: test-support/helpers/ember-tooltips.js [hunk 1]
```diff
@@ -101,9 +105,9 @@ function validateSide(side, testHelper = 'assertTooltipSide') {
 }
 
 function getTooltipAndTargetPosition(options = {}) {
-  const $target = getTooltipTargetFromBody(options.targetSelector);
+  const $target = getTooltipTargetFromBody(options.targetSelector || tooltipOrPopoverTargetSelector);
```
Comment (sir-dunxalot) [inline test-support/helpers/ember-tooltips.js]: This param was unintentionally passing in `null` as the selector causing elements to be incorrectly selected.

File: test-support/helpers/ember-tooltips.js [hunk 2]
```diff
@@ -112,6 +116,18 @@ function getTooltipAndTargetPosition(options = {}) {
   };
 }
 
+/* TODO(Duncan): Document */
+
+export function findTooltip(selector = tooltipOrPopoverSelector) {
```
Comment (sir-dunxalot) [inline test-support/helpers/ember-tooltips.js]: Technically this makes `findTooltip` and `findTooltipTarget` new public test helpers but I'm not going to document and officially release them until the PR for expanding and improving the test helpers documentation is released.

File: test-support/helpers/ember-tooltips.js [hunk 3]
```diff
@@ -123,7 +139,7 @@ export function triggerTooltipTargetEvent($element, type, options={}) {
   let wasEventTriggered = false;
 
   if (options.selector) {
-    $element = $element.find(options.selector);
+    $element = getTooltipTargetFromBody(options.selector);
```
Comment (sir-dunxalot) [inline test-support/helpers/ember-tooltips.js]: This change and other similar changes were necessary as a part of this PR because tooltips are no longer guaranteed to be children of the elements we were previously finding tooltips under. For example, in this case `$element` did not contain many of the tooltips we were looking for.

File: tests/integration/components/side-test.js [hunk 4]
```diff
@@ -13,7 +13,7 @@ test('tooltip-on-element shows on the top by default', function(assert) {
 
   assert.expect(1);
 
-  this.render(hbs`{{tooltip-on-element keepInWindow=false}}`);
+  this.render(hbs`{{tooltip-on-element keepInWindow=false effect='none'}}`);
```
Comment (sir-dunxalot) [inline tests/integration/components/side-test.js]: Added because the `effect` class was causing spacing to be incorrect. The default `'fade'` effect moves about `10px` closer to the target prior to the tooltip being animated when the tooltip is shown.

File: .travis.yml [hunk 5]
```diff
@@ -11,7 +11,6 @@ cache:
     - $HOME/.cache # includes bower's cache
 
 env:
-  - EMBER_TRY_SCENARIO=ember-1.13
```
Comment (a15n) [inline .travis.yml]: are we dropping support for ember 1-13? Zenefits is still on 1.13

File: package.json [hunk 6]
```diff
@@ -41,7 +41,7 @@
     "ember-export-application-global": "^1.0.5",
     "ember-load-initializers": "^0.5.1",
     "ember-resolver": "^2.0.3",
-    "ember-tether": "0.3.1",
+    "ember-tether": "0.4.0",
```
Comment (a15n) [inline package.json]: this version is not supported for ember versions less than 2.4.0

File: tests/dummy/config/environment.js [hunk 7]
```diff
@@ -48,8 +48,8 @@ module.exports = function(environment) {
 
   if (environment === 'production') {
     ENV.locationType = 'hash';
-    ENV.baseURL = '/ember-tooltips/';
-    ENV.baseURL = '/ember-tooltips';
+    ENV.rootURL = '/ember-tooltips/';
+    ENV.rootURL = '/ember-tooltips';
```
Comment (a15n) [inline tests/dummy/config/environment.js]: good fixes. If this PR doesn't land because we decide to support 1.13 let's do this in a separate PR

File: tests/integration/components/popover/event-bubbling-test.js [hunk 8]
```diff
@@ -0,0 +1,70 @@
+import Ember from 'ember';
+import { moduleForComponent, test } from 'ember-qunit';
+import {
+  assertTooltipNotVisible,
+  assertTooltipRendered,
+  triggerTooltipTargetEvent,
+} from '../../../helpers/ember-tooltips';
```
Comment (a15n) [inline tests/integration/components/popover/event-bubbling-test.js]: should we use the syntax we recommend in the README?

`import { ... } from <app-name/helpers/ember-tooltips>`

File: tests/integration/components/popover/event-bubbling-test.js [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+
+    assert.ok(true,
+      'The eventhandler should be fired');
+
+  });
+
+  this.render(hbs`
+    {{#some-component}}
+      {{#popover-on-component}}
+        <button class="test-button-with-action" {{action 'testaction'}}>test button</button>
```
Comment (a15n) [inline tests/integration/components/popover/event-bubbling-test.js]: could `testaction` be camelCase?

File: tests/integration/components/side-test.js [hunk 10]
```diff
@@ -1,19 +1,25 @@
...
 moduleForComponent('tooltip-on-element', 'Integration | Option | side and keepInWindow', {
   integration: true,
 });
 
 /* Test the positions without forcing the tooltip
-to stay in the window. */
+to stay in the window.
+
+It's necessary to use effect='none' because the `effect` class causes
+spacing to be incorrect. The default `'fade'` effect moves about `10px`
```
Comment (a15n) [inline tests/integration/components/side-test.js]: I don't think ticks around quotes does anything in a JS comment

File: tests/integration/components/side-test.js (hunk 4 above)
Comment (a15n) [inline tests/integration/components/side-test.js]: was this failing because of introductions in this PR?

File: tests/integration/components/spacing-test.js [hunk 11]
```diff
@@ -44,6 +44,7 @@ test('tooltip-on-element shows with spacing=20 and side=right', function(assert)
 
   this.render(hbs`
     {{tooltip-on-element
+       effect='none'
```
Comment (a15n) [inline tests/integration/components/spacing-test.js]: possible spacing issue

File: .travis.yml (hunk 5 above)
Comment (humanchimp) [inline .travis.yml]: I looked into this, but I believe that 1.4.0 is a typo. I think he meant 0.4.0, which is the latest release

Comment (humanchimp) [inline .travis.yml]: Upon closer look, it seems to refer to the [1.4.0 release of Hubspot Tether](https://github.com/HubSpot/tether/releases/tag/v1.4.0)

**Comment by humanchimp** [comment]
Given the fact that Ember 1.13 support is important to some companies, could we not do something like [what is recommended in this comment](https://github.com/sir-dunxalot/ember-tooltips/pull/169#issuecomment-274296843), and then stipulate that the app must use at least version 2.x of Ember if it wants to specify a `rootElement` other than `body`?

File: .travis.yml (hunk 5 above)
Comment (sir-dunxalot) [inline .travis.yml]: Correct. `1.4.0` of tether is required to set the equivalent of `rootElement` on the tether library.

**Comment by sir-dunxalot** [comment]
As you have both noted, I don't forsee us being able to drop support for 1.13. [This comment](https://github.com/sir-dunxalot/ember-tooltips/pull/169#issuecomment-274296843) indeed presents a good option for resolving this. However, I wonder what long-term implications including and excluding features based on ember version (rather than graceful fallback) will have on this library's maintainability and ease of contribution.

I am ok proceeding with the comment's approach but I have one other idea. I believe the reason ember-tether dropped support for Ember 1.13 at version `0.4.0` was due to the use of `getOwner()` [here](https://github.com/yapplabs/ember-tether/commit/c77f0eca62961e1d5d3992823ff3e95282b9991e#diff-80f729b5d5cad396403c71ae6e99f0abR170). We could override the `emberTetherConfig` meaning `getOwner()` is not necessary (or we could use the [available polyfill](https://github.com/rwjblue/ember-getowner-polyfill)). Perhaps we could opena PR to ember-tether that uses the polyfill when the Ember version is < 2.0.0.

Any thoughts?

**Comment by humanchimp** [comment]
I like the idea of fixing this upstream, in ember-tether. I opened https://github.com/yapplabs/ember-tether/pull/41, adding the `Ember.getOwner` polyfill, and it seems like the tests are passing.

**Comment by sir-dunxalot** [comment]
Awesome. That's plan A then. When we have an update (on whether or not @humanchimp's PR is rejected by the ember-tether guys) we'll regroup here.

**Comment by humanchimp** [comment]
Now that the ember-tether folks merged my PR, I think work on this PR is unblocked. Thanks for the gentle nudge, @sir-dunxalot. Can I help get this PR over the finish line?

File: tests/integration/components/side-test.js (hunk 4 above)
Comment (sir-dunxalot) [inline tests/integration/components/side-test.js]: I'm not sure if it was this PR that broke it or if this test was actually passing but not actually doing what we wanted.

**Comment by sir-dunxalot** [comment]
@humanchimp Yep - I'll wrap this up today.

File: .editorconfig [hunk 12]
```diff
@@ -13,22 +13,8 @@ insert_final_newline = true
 indent_style = space
```
Comment (sir-dunxalot) [inline .editorconfig]: This file was changed by the Ember upgrade.

File: .gitignore [hunk 13]
```diff
@@ -13,5 +13,5 @@
 /connect.lock
 /coverage/*
 /libpeerconnection.log
-npm-debug.log
+npm-debug.log*
```
Comment (sir-dunxalot) [inline .gitignore]: This file was changed by the Ember upgrade.

File: .jshintrc [hunk 14]
```diff
@@ -0,0 +1,32 @@
+{
```
Comment (sir-dunxalot) [inline .jshintrc]: TODO: Remove this file - was added in by the Ember CLI update.

File: .travis.yml [hunk 15]
```diff
@@ -8,9 +8,10 @@ sudo: false
 cache:
```
Comment (sir-dunxalot) [inline .travis.yml]: This file was changed by the Ember CLI upgrade.

File: bower.json [hunk 16]
```diff
@@ -1,12 +1,4 @@
 {
```
Comment (sir-dunxalot) [inline bower.json]: This file was changed by the Ember CLI upgrade.

File: config/ember-try.js [hunk 17]
```diff
@@ -10,6 +10,11 @@ module.exports = {
         resolutions: {
```
Comment (sir-dunxalot) [inline config/ember-try.js]: This file was changed by the Ember CLI upgrade.

File: LICENSE.md [hunk 18]
```diff
@@ -1,6 +1,6 @@
 The MIT License (MIT)
```
Comment (sir-dunxalot) [inline LICENSE.md]: This file was changed by the Ember CLI upgrade.

File: package.json [hunk 19]
```diff
@@ -2,66 +2,65 @@
...
+  "repository": "",
   "scripts": {
     "build": "ember build",
     "start": "ember server",
     "test": "ember try:each"
   },
-  "repository": "https://github.com/sir-dunxalot/ember-tooltips",
-  "engines": {
-    "node": ">= 0.10.0"
+  "dependencies": {
```
Comment (sir-dunxalot) [inline package.json]: This file was changed by the Ember CLI upgrade.

File: tests/.jshintrc [hunk 20]
```diff
@@ -0,0 +1,52 @@
+{
```
Comment (sir-dunxalot) [inline tests/.jshintrc]: TODO: Remove this file. It was added back in by the Ember CLI update.

File: tests/dummy/app/index.html [hunk 21]
```diff
@@ -9,17 +9,17 @@
```
Comment (sir-dunxalot) [inline tests/dummy/app/index.html]: This file was changed by the Ember CLI upgrade.

File: tests/dummy/app/router.js [hunk 22]
```diff
@@ -4,6 +4,7 @@ import config from './config/environment';
 const { Router } = Ember;
```
Comment (sir-dunxalot) [inline tests/dummy/app/router.js]: This file was changed by the Ember CLI upgrade.

File: tests/index.html [hunk 23]
```diff
@@ -10,9 +10,9 @@
     {{content-for "head"}}
```
Comment (sir-dunxalot) [inline tests/index.html]: This file was changed by the Ember CLI upgrade.

**Comment by sir-dunxalot** [comment]
After updating to ember-tether `0.4.1`, certain tests began failing with a node-related DOM error. Additionally, the test suite would hand and time out in PhantomJS browsers (similar to ember-cli/ember-cli#5415). I was able to get around these issues by updating our dependencies - notably Ember CLI. As such, a number of new file changes have been added and the scope of the PR has increased. I was unable to get around the test suite issues any other way but am open to other ideas.

@a15n - would you be able to test the installation of this branch in your Ember 1.13 project? I would like to make sure no regressions have been created for Ember 1.13 apps in either the install (via `ember install ember-tooltips`) or functionality.

Besides me removing three files accidentally added back in by the Ember CLI upgrade, I believe this PR is ready for a final review.

**Comment by a15n** [comment]
@sir-dunxalot and @humanchimp thanks so much for your hard work on this! 

There are a lot of moving parts in this PR and a lot of moving parts within Zenefits making testing these changes a somewhat long process on my end. It'll take us quite a while so I wouldn't feel comfortable holding up the process on my end waiting for that to complete.

How do you feel about releasing this as `2.9.0-beta-0`?

**Comment by humanchimp** [comment]
> How do you feel about releasing this as 2.9.0-beta-0?

Seems reasonable to me

**Comment by sir-dunxalot** [comment]
Agree that a pre-release is the best path here. I will keep this PR going into master and will release the code as a pre-release today.

**Comment by sir-dunxalot** [comment]
Released as [2.9.0-beta.0](https://github.com/sir-dunxalot/ember-tooltips/releases/tag/2.9.0-beta.0).

**Comment by humanchimp** [comment]
Thanks @sir-dunxalot!
